dist: xenial
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install mock coverage flake8
script:
  - coverage run test.py
  - coverage report --show-missing
  - flake8 ggeocoder.py
